# --- Infos Principales ---
title: ASC Balan Athlétisme
email: ascbalan@hotmail.fr
description: >-
  Site officiel de l'ASC Balan Athlétisme. Club de course à pied hors stade,
  trail et running dans l'Ain (01), affilié à la FFA.
minimal_mistakes_skin: contrast
search: true
logo: "/assets/images/logo-balan2.png"

# --- Paramètres de construction ---
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# --- URLs et Permaliens ---
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Paris

# --- Structure des dossiers (Ta demande) ---
include:
  - _pages

# --- Exclusions (Pour ne pas ralentir le site) ---
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .Rproj.user
  - "*.Rproj"
  - .gitignore
  - .sass-cache

# --- Plugins ---
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# --- Auteur / Barre latérale ---
author:
  name   : "ASC Balan"
  avatar : "/assets/images/logo-balan2.png" # <-- Ton nouveau logo ici
  bio    : "Club de course à pied route (et trail) à Balan"
  location: "Balan, Ain (01)"
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/ascbalan01/"
    - label: "Contact Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ascbalan@hotmail.fr"

# --- Pied de page ---
footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/ascbalan01/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ascbalan@hotmail.fr"

# --- Configuration des mises en page (Defaults) ---
defaults:
  # 1. Pour les articles de blog (dans _posts)
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

  # 2. Pour les pages fixes rangées dans le dossier "_pages" (Ta structure)
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      permalink: /:basename/ # Permet d'avoir mapage.html sans le dossier devant
