# --- Infos Principales ---
title: ASC Balan Athlétisme
email: ascbalan@hotmail.fr
description: >-
  Site officiel de l'ASC Balan Athlétisme. Club de course à pied hors stade,
  trail et running dans l'Ain (01), affilié à la FFA.
minimal_mistakes_skin: contrast
search: true
logo: "/assets/images/logo-balan2.png"
#url: "https://balan-running.github.io"
#baseurl: "/site-web"
url: "https://balan-running.fr"
baseurl: ""

# --- Paramètres de construction ---
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# --- URLs et Permaliens ---
permalink: /:categories/:year/:title/
paginate: 5
paginate_path: /page:num/
date_format: "%d/%m/%Y"  # "%-d %B %Y"
locale: fr-FR
timezone: Europe/Paris

# --- Structure des dossiers (Ta demande) ---
include:
  - _pages

# --- Exclusions (Pour ne pas ralentir le site) ---
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .Rproj.user
  - .Rhistory
  - "*.Rproj"
  - .gitignore
  - .sass-cache
  - HOW_TO_JEKYLL.md
  - jekyll-serve.R

# --- Plugins ---
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# --- Pied de page ---
footer:
  since: 1977
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ascbalan@hotmail.fr"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/ascbalan01/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/p/ASC-BALAN-100057064285597/"

# --- Configuration des mises en page (Defaults) ---
defaults:
  # 1. Pour les articles de blog (dans _posts)
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      show_date: true
      comments: false
      share: true
      related: true
      sidebar:
        # A copier dans _pages/actus.md aussi !
        - title: "La Bielleuse 2023-2024"
          image: "/assets/images/bielle-2025.jpg"
          text: "Félicitations à Sylvie, élue lors de l'AG de début 2025, pour l'ensemble de son œuvre !<br><br>"
        - title: "Le Bielleur 2022-2023"
          image: "/assets/images/bielle-2024.jpg"
          text: "Félicitations à Vincent, élu lors de l'AG de début 2024, pour l'ensemble de son œuvre !"

  # 2. Pour les pages fixes rangées dans le dossier "_pages" (Ta structure)
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: false
      permalink: /:basename/ # Permet d'avoir mapage.html sans le dossier devant
